# YAML configuration for an ASP.NET Core (.NET Framework) pipeline
# Triggered by changes in the 'main' branch, using a Windows VM image for the build
# Defines variables for solution, build platform, and build configuration
# Includes steps for NuGet installation, solution restore, VS build, and VSTest

# Trigger the pipeline on changes in the 'main' branch
trigger:
- main

# Use a Windows VM image for the build
pool:
  vmImage: 'windows-latest'

# Define variables for the solution, build platform, and build configuration
variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

# Define the build steps
steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    msbuildArgs: '/p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation="$(build.artifactStagingDirectory)\WebApp.zip" /p:DeployIisAppPath="Default Web Site"'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

- task: PublishBuildArtifacts@1
inputs:
  PathtoPublish: '$(build.artifactStagingDirectory)'
  ArtifactName: 'drop'
  publish
